export const QuestIdMap = {
  HighScore: "area-contest-001",
  DailyCoin: "area-daily-001",
  DailyGold: "area-daily-002",
  DailyFilm: "area-daily-003",
  DailySP: "area-daily-sp-\\d{2}-\\d{4}",
  TowerMoon: "area-ex-tower-001",
  TowerSun: "area-ex-tower-002",
  TowerTri: "area-ex-tower-003",
  TowerLiz: "area-ex-tower-004",
  MainLive: "area-main-\\d{3}",
  TowerVenus: "area-tower-001",
  BattlePvp: "",
  BattleGvg: "",
  BattleLeague: "",
}
